version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing serverless
      - npm install -g serverless
      - echo Installing todo API dependencies
      - cd backend
      - npm install
      - echo Finished installing todo API dependencies
  build:
    commands:
      - echo Deploying todo API
      - serverless deploy
      - echo Finished deploying todo API

cache:
  paths:
    - "backend/node_modules/**/*"
