service: mybackend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2

functions:
  listTodos:
    handler: handler.listTodos
    events:
      - http:
          path: todo/list
          method: get
